### ISSUE TITLE
Sprint 1

### ISSUE THREAD

**Issue by mypleasure370** [cs-utulsa/Encrypted-Chat-Service#19]
# Sprint 1
### Due: Oct 13th
- sprint goal: milestone MVP, getting framework, have encryption picked out, Python UI list
- To Do: 
- [x] Email Sprint Goal
- [x] document template
- [x] Github additions
- [x] Documentation proof-read

## Task 1: Product Vision
- [x] vision and goals (proposed functionality, user experience, value)
- [x] Distinct product qualities 

## Task 2: Hardware and Software
- [x] Pick hardware/software support
- [x] Pick languages

## Task 3: Product Backlog
- include value to users, estimated effort, prioritize based on value and effort
- [x] User stories

## Task 4: Sprint goals and backlog
- [x] sprint goal and plan
   - segmented into parts like example
   - estimation of effort and priority
   - who is assigned to each task
- [x] burndown chart

## Task 5: GitHub maintenance
- [x] update product backlog, sprint backlog, and associated fields

## Task 6: Sprint-specific assignment
- [x] Architecture diagram 
    - demo?
    - Sprint 2: demo of MVP
    - Sprint 3: kickstarter video
- [x] Presentation
    - Slides
    - Demo

**Comment by tuckplace** [comment]
All Content should be present and ready to be put into the document
