### ISSUE TITLE
Sprint 2

### ISSUE THREAD

**Issue by tuckplace** [cs-utulsa/Encrypted-Chat-Service#20]
# Sprint 2
### Due: Nov 3rd
- sprint goal: MVP testing, working encryption in QA, GUI option picked out, and further research on its use. 
- To Do: 
- [x] Email Sprint Goal
- [ ] document template
- [x] Github additions
- [x] Documentation proof-read

## Task 1: Product Vision
- [x] review vision and goals (proposed functionality, user experience, value)
- [x] review/update distinct product qualities 

## Task 2: Hardware and Software
- [x] add program language (python)

## Task 3: Product Backlog
- include value to users, estimated effort, prioritize based on value and effort
- [x] Add user stories to everything

## Task 4: Sprint goals and backlog
- [x] sprint goal and plan
   - segmented into parts like example
   - estimation of effort and priority
   - who is assigned to each task
   - **add kickstarter video prep to backlog**
- [x] burndown chart
- [x] everyone's summary of efforts

## Task 5: GitHub maintenance
- [x] update product backlog, sprint backlog, and associated fields

## Task 6: Sprint-specific assignment
- [x] Architecture diagram 
    - demo of MVP
- [x] Presentation
    - Slides
    - Demo
- [ ] start planning Kickstarter video for sprint 3
