### ISSUE TITLE
Sprint 3

### ISSUE THREAD

**Issue by tuckplace** [cs-utulsa/Encrypted-Chat-Service#23]
# Sprint 3
### Due: Dec 1st
- Sprint Goal: Encryption testing, basic GUI, Research on file transfer
- To Do: 
- [ ] Email Sprint Goal
- [ ] document template
- [ ] Github additions
- [ ] Documentation proof-read

## Task 1: Product Vision
- [ ] vision and goals (proposed functionality, user experience, value)
- [ ] Distinct product qualities 

## Task 2: Hardware and Software
- [ ] Pick hardware/software support
- [ ] Pick languages

## Task 3: Product Backlog
- include value to users, estimated effort, prioritize based on value and effort
- [ ] User stories

## Task 4: Sprint goals and backlog
- [ ] sprint goal and plan
   - segmented into parts like example
   - estimation of effort and priority
   - who is assigned to each task
- [ ] burndown chart

## Task 5: GitHub maintenance
- [ ] update product backlog, sprint backlog, and associated fields

## Task 6: Sprint-specific assignment
- [ ] Architecture diagram 
    - demo?
    - Sprint 2: demo of MVP
    - Sprint 3: kickstarter video
- [ ] Presentation
    - Slides
    - Demo

**Comment by tuckplace** [comment]
Sprint goals: Testing Client, Chat and Server classes. Encryption add in. Research on GUI options.
