### ISSUE TITLE
Sprint 3

### ISSUE THREAD

**Issue by tuckplace** [cs-utulsa/Encrypted-Chat-Service#49]
# Sprint 2
### Due: Nov 3rd
- sprint goal: MVP testing, working encryption in QA, GUI option picked out, and further research on its use. 
- To Do: 
- [ ] Email Sprint Goal
- [ ] document template
- [ ] Github additions
- [ ] Documentation proof-read

## Task 1: Product Vision
- [ ] review vision and goals (proposed functionality, user experience, value)
- [ ] review/update distinct product qualities 

## Task 2: Hardware and Software
- [ ] add program language (python)

## Task 3: Product Backlog
- include value to users, estimated effort, prioritize based on value and effort
- [ ] Add user stories to everything

## Task 4: Sprint goals and backlog
- [ ] sprint goal and plan
   - segmented into parts like example
   - estimation of effort and priority
   - who is assigned to each task
   - **add kickstarter video prep to backlog**
- [ ] burndown chart
- [ ] everyone's summary of efforts

## Task 5: GitHub maintenance
- [ ] update product backlog, sprint backlog, and associated fields

## Task 6: Sprint-specific assignment
- [ ] Architecture diagram 
    - demo of MVP
- [ ] Presentation
    - Slides
    - Demo
- [ ] start planning Kickstarter video for sprint 3

**Comment by tuckplace** [comment]
Sprint goals: Create functional GUI screens for Startup, Connection and Chat. This should also include necessary prompts. As well as our Kickstarter video, encryption enhancements and encryption testing.
